/* tslint:disable */
/* eslint-disable */
/**
 * Gym Manager Swagger
 * Gym Manager REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 회원권 테이블
 * @export
 * @interface Membership
 */
export interface Membership {
    /**
     * 회원권 명
     * @type {string}
     * @memberof Membership
     */
    membershipName?: string;
    /**
     * 회원권 기간
     * @type {string}
     * @memberof Membership
     */
    membershipPeriod?: string;
    /**
     * 회원권 시퀀스
     * @type {number}
     * @memberof Membership
     */
    membershipSeq?: number;
    /**
     * 등록 일자
     * @type {Date}
     * @memberof Membership
     */
    regDate?: Date;
    /**
     * 등록자 ID
     * @type {string}
     * @memberof Membership
     */
    regId?: string;
    /**
     * 사업장 시퀀스
     * @type {number}
     * @memberof Membership
     */
    wpSeq?: number;
}

/**
 * Check if a given object implements the Membership interface.
 */
export function instanceOfMembership(value: object): value is Membership {
    return true;
}

export function MembershipFromJSON(json: any): Membership {
    return MembershipFromJSONTyped(json, false);
}

export function MembershipFromJSONTyped(json: any, ignoreDiscriminator: boolean): Membership {
    if (json == null) {
        return json;
    }
    return {
        
        'membershipName': json['membershipName'] == null ? undefined : json['membershipName'],
        'membershipPeriod': json['membershipPeriod'] == null ? undefined : json['membershipPeriod'],
        'membershipSeq': json['membershipSeq'] == null ? undefined : json['membershipSeq'],
        'regDate': json['regDate'] == null ? undefined : (new Date(json['regDate'])),
        'regId': json['regId'] == null ? undefined : json['regId'],
        'wpSeq': json['wpSeq'] == null ? undefined : json['wpSeq'],
    };
}

export function MembershipToJSON(json: any): Membership {
    return MembershipToJSONTyped(json, false);
}

export function MembershipToJSONTyped(value?: Membership | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'membershipName': value['membershipName'],
        'membershipPeriod': value['membershipPeriod'],
        'membershipSeq': value['membershipSeq'],
        'regDate': value['regDate'] == null ? undefined : ((value['regDate']).toISOString()),
        'regId': value['regId'],
        'wpSeq': value['wpSeq'],
    };
}

