/* tslint:disable */
/* eslint-disable */
/**
 * Gym Manager Swagger
 * Gym Manager REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SalesChartVO } from './SalesChartVO';
import {
    SalesChartVOFromJSON,
    SalesChartVOFromJSONTyped,
    SalesChartVOToJSON,
    SalesChartVOToJSONTyped,
} from './SalesChartVO';

/**
 * 
 * @export
 * @interface ResponseListVOSalesChartVO
 */
export interface ResponseListVOSalesChartVO {
    /**
     * 현재 페이지 번호
     * @type {number}
     * @memberof ResponseListVOSalesChartVO
     */
    currentPageNo?: number;
    /**
     * 
     * @type {Array<SalesChartVO>}
     * @memberof ResponseListVOSalesChartVO
     */
    list?: Array<SalesChartVO>;
    /**
     * 페이지당 보여주는 레코드 수
     * @type {number}
     * @memberof ResponseListVOSalesChartVO
     */
    recordCountPerPage?: number;
    /**
     * 전체 개수
     * @type {number}
     * @memberof ResponseListVOSalesChartVO
     */
    totalCnt?: number;
}

/**
 * Check if a given object implements the ResponseListVOSalesChartVO interface.
 */
export function instanceOfResponseListVOSalesChartVO(value: object): value is ResponseListVOSalesChartVO {
    return true;
}

export function ResponseListVOSalesChartVOFromJSON(json: any): ResponseListVOSalesChartVO {
    return ResponseListVOSalesChartVOFromJSONTyped(json, false);
}

export function ResponseListVOSalesChartVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseListVOSalesChartVO {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPageNo': json['currentPageNo'] == null ? undefined : json['currentPageNo'],
        'list': json['list'] == null ? undefined : ((json['list'] as Array<any>).map(SalesChartVOFromJSON)),
        'recordCountPerPage': json['recordCountPerPage'] == null ? undefined : json['recordCountPerPage'],
        'totalCnt': json['totalCnt'] == null ? undefined : json['totalCnt'],
    };
}

export function ResponseListVOSalesChartVOToJSON(json: any): ResponseListVOSalesChartVO {
    return ResponseListVOSalesChartVOToJSONTyped(json, false);
}

export function ResponseListVOSalesChartVOToJSONTyped(value?: ResponseListVOSalesChartVO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currentPageNo': value['currentPageNo'],
        'list': value['list'] == null ? undefined : ((value['list'] as Array<any>).map(SalesChartVOToJSON)),
        'recordCountPerPage': value['recordCountPerPage'],
        'totalCnt': value['totalCnt'],
    };
}

