/* tslint:disable */
/* eslint-disable */
/**
 * Gym Manager Swagger
 * Gym Manager REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseListVOVisitHistory } from './ResponseListVOVisitHistory';
import {
    ResponseListVOVisitHistoryFromJSON,
    ResponseListVOVisitHistoryFromJSONTyped,
    ResponseListVOVisitHistoryToJSON,
    ResponseListVOVisitHistoryToJSONTyped,
} from './ResponseListVOVisitHistory';

/**
 * 
 * @export
 * @interface ResponseJsonResponseListVOVisitHistory
 */
export interface ResponseJsonResponseListVOVisitHistory {
    /**
     * 
     * @type {string}
     * @memberof ResponseJsonResponseListVOVisitHistory
     */
    message?: string;
    /**
     * 
     * @type {ResponseListVOVisitHistory}
     * @memberof ResponseJsonResponseListVOVisitHistory
     */
    result?: ResponseListVOVisitHistory;
    /**
     * 
     * @type {number}
     * @memberof ResponseJsonResponseListVOVisitHistory
     */
    status?: number;
}

/**
 * Check if a given object implements the ResponseJsonResponseListVOVisitHistory interface.
 */
export function instanceOfResponseJsonResponseListVOVisitHistory(value: object): value is ResponseJsonResponseListVOVisitHistory {
    return true;
}

export function ResponseJsonResponseListVOVisitHistoryFromJSON(json: any): ResponseJsonResponseListVOVisitHistory {
    return ResponseJsonResponseListVOVisitHistoryFromJSONTyped(json, false);
}

export function ResponseJsonResponseListVOVisitHistoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseJsonResponseListVOVisitHistory {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : ResponseListVOVisitHistoryFromJSON(json['result']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ResponseJsonResponseListVOVisitHistoryToJSON(json: any): ResponseJsonResponseListVOVisitHistory {
    return ResponseJsonResponseListVOVisitHistoryToJSONTyped(json, false);
}

export function ResponseJsonResponseListVOVisitHistoryToJSONTyped(value?: ResponseJsonResponseListVOVisitHistory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'result': ResponseListVOVisitHistoryToJSON(value['result']),
        'status': value['status'],
    };
}

