/* tslint:disable */
/* eslint-disable */
/**
 * Gym Manager Swagger
 * Gym Manager REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VisitChartVO } from './VisitChartVO';
import {
    VisitChartVOFromJSON,
    VisitChartVOFromJSONTyped,
    VisitChartVOToJSON,
    VisitChartVOToJSONTyped,
} from './VisitChartVO';

/**
 * 
 * @export
 * @interface ResponseListVOVisitChartVO
 */
export interface ResponseListVOVisitChartVO {
    /**
     * 현재 페이지 번호
     * @type {number}
     * @memberof ResponseListVOVisitChartVO
     */
    currentPageNo?: number;
    /**
     * 
     * @type {Array<VisitChartVO>}
     * @memberof ResponseListVOVisitChartVO
     */
    list?: Array<VisitChartVO>;
    /**
     * 페이지당 보여주는 레코드 수
     * @type {number}
     * @memberof ResponseListVOVisitChartVO
     */
    recordCountPerPage?: number;
    /**
     * 전체 개수
     * @type {number}
     * @memberof ResponseListVOVisitChartVO
     */
    totalCnt?: number;
}

/**
 * Check if a given object implements the ResponseListVOVisitChartVO interface.
 */
export function instanceOfResponseListVOVisitChartVO(value: object): value is ResponseListVOVisitChartVO {
    return true;
}

export function ResponseListVOVisitChartVOFromJSON(json: any): ResponseListVOVisitChartVO {
    return ResponseListVOVisitChartVOFromJSONTyped(json, false);
}

export function ResponseListVOVisitChartVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseListVOVisitChartVO {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPageNo': json['currentPageNo'] == null ? undefined : json['currentPageNo'],
        'list': json['list'] == null ? undefined : ((json['list'] as Array<any>).map(VisitChartVOFromJSON)),
        'recordCountPerPage': json['recordCountPerPage'] == null ? undefined : json['recordCountPerPage'],
        'totalCnt': json['totalCnt'] == null ? undefined : json['totalCnt'],
    };
}

export function ResponseListVOVisitChartVOToJSON(json: any): ResponseListVOVisitChartVO {
    return ResponseListVOVisitChartVOToJSONTyped(json, false);
}

export function ResponseListVOVisitChartVOToJSONTyped(value?: ResponseListVOVisitChartVO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currentPageNo': value['currentPageNo'],
        'list': value['list'] == null ? undefined : ((value['list'] as Array<any>).map(VisitChartVOToJSON)),
        'recordCountPerPage': value['recordCountPerPage'],
        'totalCnt': value['totalCnt'],
    };
}

