/* tslint:disable */
/* eslint-disable */
/**
 * Gym Manager Swagger
 * Gym Manager REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MembershipVO } from './MembershipVO';
import {
    MembershipVOFromJSON,
    MembershipVOFromJSONTyped,
    MembershipVOToJSON,
    MembershipVOToJSONTyped,
} from './MembershipVO';

/**
 * 
 * @export
 * @interface ResponseListVOMembershipVO
 */
export interface ResponseListVOMembershipVO {
    /**
     * 현재 페이지 번호
     * @type {number}
     * @memberof ResponseListVOMembershipVO
     */
    currentPageNo?: number;
    /**
     * 
     * @type {Array<MembershipVO>}
     * @memberof ResponseListVOMembershipVO
     */
    list?: Array<MembershipVO>;
    /**
     * 페이지당 보여주는 레코드 수
     * @type {number}
     * @memberof ResponseListVOMembershipVO
     */
    recordCountPerPage?: number;
    /**
     * 전체 개수
     * @type {number}
     * @memberof ResponseListVOMembershipVO
     */
    totalCnt?: number;
}

/**
 * Check if a given object implements the ResponseListVOMembershipVO interface.
 */
export function instanceOfResponseListVOMembershipVO(value: object): value is ResponseListVOMembershipVO {
    return true;
}

export function ResponseListVOMembershipVOFromJSON(json: any): ResponseListVOMembershipVO {
    return ResponseListVOMembershipVOFromJSONTyped(json, false);
}

export function ResponseListVOMembershipVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseListVOMembershipVO {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPageNo': json['currentPageNo'] == null ? undefined : json['currentPageNo'],
        'list': json['list'] == null ? undefined : ((json['list'] as Array<any>).map(MembershipVOFromJSON)),
        'recordCountPerPage': json['recordCountPerPage'] == null ? undefined : json['recordCountPerPage'],
        'totalCnt': json['totalCnt'] == null ? undefined : json['totalCnt'],
    };
}

export function ResponseListVOMembershipVOToJSON(json: any): ResponseListVOMembershipVO {
    return ResponseListVOMembershipVOToJSONTyped(json, false);
}

export function ResponseListVOMembershipVOToJSONTyped(value?: ResponseListVOMembershipVO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currentPageNo': value['currentPageNo'],
        'list': value['list'] == null ? undefined : ((value['list'] as Array<any>).map(MembershipVOToJSON)),
        'recordCountPerPage': value['recordCountPerPage'],
        'totalCnt': value['totalCnt'],
    };
}

