/* tslint:disable */
/* eslint-disable */
/**
 * Gym Manager Swagger
 * Gym Manager REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VisitHistory } from './VisitHistory';
import {
    VisitHistoryFromJSON,
    VisitHistoryFromJSONTyped,
    VisitHistoryToJSON,
    VisitHistoryToJSONTyped,
} from './VisitHistory';

/**
 * 
 * @export
 * @interface ResponseListVOVisitHistory
 */
export interface ResponseListVOVisitHistory {
    /**
     * 현재 페이지 번호
     * @type {number}
     * @memberof ResponseListVOVisitHistory
     */
    currentPageNo?: number;
    /**
     * 
     * @type {Array<VisitHistory>}
     * @memberof ResponseListVOVisitHistory
     */
    list?: Array<VisitHistory>;
    /**
     * 페이지당 보여주는 레코드 수
     * @type {number}
     * @memberof ResponseListVOVisitHistory
     */
    recordCountPerPage?: number;
    /**
     * 전체 개수
     * @type {number}
     * @memberof ResponseListVOVisitHistory
     */
    totalCnt?: number;
}

/**
 * Check if a given object implements the ResponseListVOVisitHistory interface.
 */
export function instanceOfResponseListVOVisitHistory(value: object): value is ResponseListVOVisitHistory {
    return true;
}

export function ResponseListVOVisitHistoryFromJSON(json: any): ResponseListVOVisitHistory {
    return ResponseListVOVisitHistoryFromJSONTyped(json, false);
}

export function ResponseListVOVisitHistoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseListVOVisitHistory {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPageNo': json['currentPageNo'] == null ? undefined : json['currentPageNo'],
        'list': json['list'] == null ? undefined : ((json['list'] as Array<any>).map(VisitHistoryFromJSON)),
        'recordCountPerPage': json['recordCountPerPage'] == null ? undefined : json['recordCountPerPage'],
        'totalCnt': json['totalCnt'] == null ? undefined : json['totalCnt'],
    };
}

export function ResponseListVOVisitHistoryToJSON(json: any): ResponseListVOVisitHistory {
    return ResponseListVOVisitHistoryToJSONTyped(json, false);
}

export function ResponseListVOVisitHistoryToJSONTyped(value?: ResponseListVOVisitHistory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currentPageNo': value['currentPageNo'],
        'list': value['list'] == null ? undefined : ((value['list'] as Array<any>).map(VisitHistoryToJSON)),
        'recordCountPerPage': value['recordCountPerPage'],
        'totalCnt': value['totalCnt'],
    };
}

