/* tslint:disable */
/* eslint-disable */
/**
 * Gym Manager Swagger
 * Gym Manager REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseListVOMemberVO } from './ResponseListVOMemberVO';
import {
    ResponseListVOMemberVOFromJSON,
    ResponseListVOMemberVOFromJSONTyped,
    ResponseListVOMemberVOToJSON,
    ResponseListVOMemberVOToJSONTyped,
} from './ResponseListVOMemberVO';

/**
 * 
 * @export
 * @interface ResponseJsonResponseListVOMemberVO
 */
export interface ResponseJsonResponseListVOMemberVO {
    /**
     * 
     * @type {string}
     * @memberof ResponseJsonResponseListVOMemberVO
     */
    message?: string;
    /**
     * 
     * @type {ResponseListVOMemberVO}
     * @memberof ResponseJsonResponseListVOMemberVO
     */
    result?: ResponseListVOMemberVO;
    /**
     * 
     * @type {number}
     * @memberof ResponseJsonResponseListVOMemberVO
     */
    status?: number;
}

/**
 * Check if a given object implements the ResponseJsonResponseListVOMemberVO interface.
 */
export function instanceOfResponseJsonResponseListVOMemberVO(value: object): value is ResponseJsonResponseListVOMemberVO {
    return true;
}

export function ResponseJsonResponseListVOMemberVOFromJSON(json: any): ResponseJsonResponseListVOMemberVO {
    return ResponseJsonResponseListVOMemberVOFromJSONTyped(json, false);
}

export function ResponseJsonResponseListVOMemberVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseJsonResponseListVOMemberVO {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : ResponseListVOMemberVOFromJSON(json['result']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ResponseJsonResponseListVOMemberVOToJSON(json: any): ResponseJsonResponseListVOMemberVO {
    return ResponseJsonResponseListVOMemberVOToJSONTyped(json, false);
}

export function ResponseJsonResponseListVOMemberVOToJSONTyped(value?: ResponseJsonResponseListVOMemberVO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'result': ResponseListVOMemberVOToJSON(value['result']),
        'status': value['status'],
    };
}

