/* tslint:disable */
/* eslint-disable */
/**
 * Gym Manager Swagger
 * Gym Manager REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentsHistoryVO } from './PaymentsHistoryVO';
import {
    PaymentsHistoryVOFromJSON,
    PaymentsHistoryVOFromJSONTyped,
    PaymentsHistoryVOToJSON,
    PaymentsHistoryVOToJSONTyped,
} from './PaymentsHistoryVO';

/**
 * 
 * @export
 * @interface ResponseJsonPaymentsHistoryVO
 */
export interface ResponseJsonPaymentsHistoryVO {
    /**
     * 
     * @type {string}
     * @memberof ResponseJsonPaymentsHistoryVO
     */
    message?: string;
    /**
     * 
     * @type {PaymentsHistoryVO}
     * @memberof ResponseJsonPaymentsHistoryVO
     */
    result?: PaymentsHistoryVO;
    /**
     * 
     * @type {number}
     * @memberof ResponseJsonPaymentsHistoryVO
     */
    status?: number;
}

/**
 * Check if a given object implements the ResponseJsonPaymentsHistoryVO interface.
 */
export function instanceOfResponseJsonPaymentsHistoryVO(value: object): value is ResponseJsonPaymentsHistoryVO {
    return true;
}

export function ResponseJsonPaymentsHistoryVOFromJSON(json: any): ResponseJsonPaymentsHistoryVO {
    return ResponseJsonPaymentsHistoryVOFromJSONTyped(json, false);
}

export function ResponseJsonPaymentsHistoryVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseJsonPaymentsHistoryVO {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : PaymentsHistoryVOFromJSON(json['result']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ResponseJsonPaymentsHistoryVOToJSON(json: any): ResponseJsonPaymentsHistoryVO {
    return ResponseJsonPaymentsHistoryVOToJSONTyped(json, false);
}

export function ResponseJsonPaymentsHistoryVOToJSONTyped(value?: ResponseJsonPaymentsHistoryVO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'result': PaymentsHistoryVOToJSON(value['result']),
        'status': value['status'],
    };
}

