/* tslint:disable */
/* eslint-disable */
/**
 * Gym Manager Swagger
 * Gym Manager REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CalendarVO } from './CalendarVO';
import {
    CalendarVOFromJSON,
    CalendarVOFromJSONTyped,
    CalendarVOToJSON,
    CalendarVOToJSONTyped,
} from './CalendarVO';

/**
 * 
 * @export
 * @interface ResponseJsonCalendarVO
 */
export interface ResponseJsonCalendarVO {
    /**
     * 
     * @type {string}
     * @memberof ResponseJsonCalendarVO
     */
    message?: string;
    /**
     * 
     * @type {CalendarVO}
     * @memberof ResponseJsonCalendarVO
     */
    result?: CalendarVO;
    /**
     * 
     * @type {number}
     * @memberof ResponseJsonCalendarVO
     */
    status?: number;
}

/**
 * Check if a given object implements the ResponseJsonCalendarVO interface.
 */
export function instanceOfResponseJsonCalendarVO(value: object): value is ResponseJsonCalendarVO {
    return true;
}

export function ResponseJsonCalendarVOFromJSON(json: any): ResponseJsonCalendarVO {
    return ResponseJsonCalendarVOFromJSONTyped(json, false);
}

export function ResponseJsonCalendarVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseJsonCalendarVO {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : CalendarVOFromJSON(json['result']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ResponseJsonCalendarVOToJSON(json: any): ResponseJsonCalendarVO {
    return ResponseJsonCalendarVOToJSONTyped(json, false);
}

export function ResponseJsonCalendarVOToJSONTyped(value?: ResponseJsonCalendarVO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'result': CalendarVOToJSON(value['result']),
        'status': value['status'],
    };
}

