/* tslint:disable */
/* eslint-disable */
/**
 * Gym Manager Swagger
 * Gym Manager REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CalendarVO } from './CalendarVO';
import {
    CalendarVOFromJSON,
    CalendarVOFromJSONTyped,
    CalendarVOToJSON,
    CalendarVOToJSONTyped,
} from './CalendarVO';

/**
 * 
 * @export
 * @interface ResponseJsonListCalendarVO
 */
export interface ResponseJsonListCalendarVO {
    /**
     * 
     * @type {string}
     * @memberof ResponseJsonListCalendarVO
     */
    message?: string;
    /**
     * 
     * @type {Array<CalendarVO>}
     * @memberof ResponseJsonListCalendarVO
     */
    result?: Array<CalendarVO>;
    /**
     * 
     * @type {number}
     * @memberof ResponseJsonListCalendarVO
     */
    status?: number;
}

/**
 * Check if a given object implements the ResponseJsonListCalendarVO interface.
 */
export function instanceOfResponseJsonListCalendarVO(value: object): value is ResponseJsonListCalendarVO {
    return true;
}

export function ResponseJsonListCalendarVOFromJSON(json: any): ResponseJsonListCalendarVO {
    return ResponseJsonListCalendarVOFromJSONTyped(json, false);
}

export function ResponseJsonListCalendarVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseJsonListCalendarVO {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : ((json['result'] as Array<any>).map(CalendarVOFromJSON)),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ResponseJsonListCalendarVOToJSON(json: any): ResponseJsonListCalendarVO {
    return ResponseJsonListCalendarVOToJSONTyped(json, false);
}

export function ResponseJsonListCalendarVOToJSONTyped(value?: ResponseJsonListCalendarVO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'result': value['result'] == null ? undefined : ((value['result'] as Array<any>).map(CalendarVOToJSON)),
        'status': value['status'],
    };
}

