/* tslint:disable */
/* eslint-disable */
/**
 * Gym Manager Swagger
 * Gym Manager REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseListVOPaymentsHistoryVO } from './ResponseListVOPaymentsHistoryVO';
import {
    ResponseListVOPaymentsHistoryVOFromJSON,
    ResponseListVOPaymentsHistoryVOFromJSONTyped,
    ResponseListVOPaymentsHistoryVOToJSON,
    ResponseListVOPaymentsHistoryVOToJSONTyped,
} from './ResponseListVOPaymentsHistoryVO';

/**
 * 
 * @export
 * @interface ResponseJsonResponseListVOPaymentsHistoryVO
 */
export interface ResponseJsonResponseListVOPaymentsHistoryVO {
    /**
     * 
     * @type {string}
     * @memberof ResponseJsonResponseListVOPaymentsHistoryVO
     */
    message?: string;
    /**
     * 
     * @type {ResponseListVOPaymentsHistoryVO}
     * @memberof ResponseJsonResponseListVOPaymentsHistoryVO
     */
    result?: ResponseListVOPaymentsHistoryVO;
    /**
     * 
     * @type {number}
     * @memberof ResponseJsonResponseListVOPaymentsHistoryVO
     */
    status?: number;
}

/**
 * Check if a given object implements the ResponseJsonResponseListVOPaymentsHistoryVO interface.
 */
export function instanceOfResponseJsonResponseListVOPaymentsHistoryVO(value: object): value is ResponseJsonResponseListVOPaymentsHistoryVO {
    return true;
}

export function ResponseJsonResponseListVOPaymentsHistoryVOFromJSON(json: any): ResponseJsonResponseListVOPaymentsHistoryVO {
    return ResponseJsonResponseListVOPaymentsHistoryVOFromJSONTyped(json, false);
}

export function ResponseJsonResponseListVOPaymentsHistoryVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseJsonResponseListVOPaymentsHistoryVO {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : ResponseListVOPaymentsHistoryVOFromJSON(json['result']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ResponseJsonResponseListVOPaymentsHistoryVOToJSON(json: any): ResponseJsonResponseListVOPaymentsHistoryVO {
    return ResponseJsonResponseListVOPaymentsHistoryVOToJSONTyped(json, false);
}

export function ResponseJsonResponseListVOPaymentsHistoryVOToJSONTyped(value?: ResponseJsonResponseListVOPaymentsHistoryVO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'result': ResponseListVOPaymentsHistoryVOToJSON(value['result']),
        'status': value['status'],
    };
}

