/* tslint:disable */
/* eslint-disable */
/**
 * Gym Manager Swagger
 * Gym Manager REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MemberVO } from './MemberVO';
import {
    MemberVOFromJSON,
    MemberVOFromJSONTyped,
    MemberVOToJSON,
    MemberVOToJSONTyped,
} from './MemberVO';

/**
 * 
 * @export
 * @interface ResponseJsonMemberVO
 */
export interface ResponseJsonMemberVO {
    /**
     * 
     * @type {string}
     * @memberof ResponseJsonMemberVO
     */
    message?: string;
    /**
     * 
     * @type {MemberVO}
     * @memberof ResponseJsonMemberVO
     */
    result?: MemberVO;
    /**
     * 
     * @type {number}
     * @memberof ResponseJsonMemberVO
     */
    status?: number;
}

/**
 * Check if a given object implements the ResponseJsonMemberVO interface.
 */
export function instanceOfResponseJsonMemberVO(value: object): value is ResponseJsonMemberVO {
    return true;
}

export function ResponseJsonMemberVOFromJSON(json: any): ResponseJsonMemberVO {
    return ResponseJsonMemberVOFromJSONTyped(json, false);
}

export function ResponseJsonMemberVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseJsonMemberVO {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : MemberVOFromJSON(json['result']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ResponseJsonMemberVOToJSON(json: any): ResponseJsonMemberVO {
    return ResponseJsonMemberVOToJSONTyped(json, false);
}

export function ResponseJsonMemberVOToJSONTyped(value?: ResponseJsonMemberVO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'result': MemberVOToJSON(value['result']),
        'status': value['status'],
    };
}

