/* tslint:disable */
/* eslint-disable */
/**
 * Gym Manager Swagger
 * Gym Manager REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseListVOMembershipVO } from './ResponseListVOMembershipVO';
import {
    ResponseListVOMembershipVOFromJSON,
    ResponseListVOMembershipVOFromJSONTyped,
    ResponseListVOMembershipVOToJSON,
    ResponseListVOMembershipVOToJSONTyped,
} from './ResponseListVOMembershipVO';

/**
 * 
 * @export
 * @interface ResponseJsonResponseListVOMembershipVO
 */
export interface ResponseJsonResponseListVOMembershipVO {
    /**
     * 
     * @type {string}
     * @memberof ResponseJsonResponseListVOMembershipVO
     */
    message?: string;
    /**
     * 
     * @type {ResponseListVOMembershipVO}
     * @memberof ResponseJsonResponseListVOMembershipVO
     */
    result?: ResponseListVOMembershipVO;
    /**
     * 
     * @type {number}
     * @memberof ResponseJsonResponseListVOMembershipVO
     */
    status?: number;
}

/**
 * Check if a given object implements the ResponseJsonResponseListVOMembershipVO interface.
 */
export function instanceOfResponseJsonResponseListVOMembershipVO(value: object): value is ResponseJsonResponseListVOMembershipVO {
    return true;
}

export function ResponseJsonResponseListVOMembershipVOFromJSON(json: any): ResponseJsonResponseListVOMembershipVO {
    return ResponseJsonResponseListVOMembershipVOFromJSONTyped(json, false);
}

export function ResponseJsonResponseListVOMembershipVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseJsonResponseListVOMembershipVO {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : ResponseListVOMembershipVOFromJSON(json['result']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ResponseJsonResponseListVOMembershipVOToJSON(json: any): ResponseJsonResponseListVOMembershipVO {
    return ResponseJsonResponseListVOMembershipVOToJSONTyped(json, false);
}

export function ResponseJsonResponseListVOMembershipVOToJSONTyped(value?: ResponseJsonResponseListVOMembershipVO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'result': ResponseListVOMembershipVOToJSON(value['result']),
        'status': value['status'],
    };
}

