/* tslint:disable */
/* eslint-disable */
/**
 * Gym Manager Swagger
 * Gym Manager REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseListVOCalendarVO } from './ResponseListVOCalendarVO';
import {
    ResponseListVOCalendarVOFromJSON,
    ResponseListVOCalendarVOFromJSONTyped,
    ResponseListVOCalendarVOToJSON,
    ResponseListVOCalendarVOToJSONTyped,
} from './ResponseListVOCalendarVO';

/**
 * 
 * @export
 * @interface ResponseJsonResponseListVOCalendarVO
 */
export interface ResponseJsonResponseListVOCalendarVO {
    /**
     * 
     * @type {string}
     * @memberof ResponseJsonResponseListVOCalendarVO
     */
    message?: string;
    /**
     * 
     * @type {ResponseListVOCalendarVO}
     * @memberof ResponseJsonResponseListVOCalendarVO
     */
    result?: ResponseListVOCalendarVO;
    /**
     * 
     * @type {number}
     * @memberof ResponseJsonResponseListVOCalendarVO
     */
    status?: number;
}

/**
 * Check if a given object implements the ResponseJsonResponseListVOCalendarVO interface.
 */
export function instanceOfResponseJsonResponseListVOCalendarVO(value: object): value is ResponseJsonResponseListVOCalendarVO {
    return true;
}

export function ResponseJsonResponseListVOCalendarVOFromJSON(json: any): ResponseJsonResponseListVOCalendarVO {
    return ResponseJsonResponseListVOCalendarVOFromJSONTyped(json, false);
}

export function ResponseJsonResponseListVOCalendarVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseJsonResponseListVOCalendarVO {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : ResponseListVOCalendarVOFromJSON(json['result']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ResponseJsonResponseListVOCalendarVOToJSON(json: any): ResponseJsonResponseListVOCalendarVO {
    return ResponseJsonResponseListVOCalendarVOToJSONTyped(json, false);
}

export function ResponseJsonResponseListVOCalendarVOToJSONTyped(value?: ResponseJsonResponseListVOCalendarVO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'result': ResponseListVOCalendarVOToJSON(value['result']),
        'status': value['status'],
    };
}

