/* tslint:disable */
/* eslint-disable */
/**
 * Gym Manager Swagger
 * Gym Manager REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseListVOSalesChartVO } from './ResponseListVOSalesChartVO';
import {
    ResponseListVOSalesChartVOFromJSON,
    ResponseListVOSalesChartVOFromJSONTyped,
    ResponseListVOSalesChartVOToJSON,
    ResponseListVOSalesChartVOToJSONTyped,
} from './ResponseListVOSalesChartVO';

/**
 * 
 * @export
 * @interface ResponseJsonResponseListVOSalesChartVO
 */
export interface ResponseJsonResponseListVOSalesChartVO {
    /**
     * 
     * @type {string}
     * @memberof ResponseJsonResponseListVOSalesChartVO
     */
    message?: string;
    /**
     * 
     * @type {ResponseListVOSalesChartVO}
     * @memberof ResponseJsonResponseListVOSalesChartVO
     */
    result?: ResponseListVOSalesChartVO;
    /**
     * 
     * @type {number}
     * @memberof ResponseJsonResponseListVOSalesChartVO
     */
    status?: number;
}

/**
 * Check if a given object implements the ResponseJsonResponseListVOSalesChartVO interface.
 */
export function instanceOfResponseJsonResponseListVOSalesChartVO(value: object): value is ResponseJsonResponseListVOSalesChartVO {
    return true;
}

export function ResponseJsonResponseListVOSalesChartVOFromJSON(json: any): ResponseJsonResponseListVOSalesChartVO {
    return ResponseJsonResponseListVOSalesChartVOFromJSONTyped(json, false);
}

export function ResponseJsonResponseListVOSalesChartVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseJsonResponseListVOSalesChartVO {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : ResponseListVOSalesChartVOFromJSON(json['result']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ResponseJsonResponseListVOSalesChartVOToJSON(json: any): ResponseJsonResponseListVOSalesChartVO {
    return ResponseJsonResponseListVOSalesChartVOToJSONTyped(json, false);
}

export function ResponseJsonResponseListVOSalesChartVOToJSONTyped(value?: ResponseJsonResponseListVOSalesChartVO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'result': ResponseListVOSalesChartVOToJSON(value['result']),
        'status': value['status'],
    };
}

