/* tslint:disable */
/* eslint-disable */
/**
 * Gym Manager Swagger
 * Gym Manager REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AccountVO,
  ResponseJsonAccountVO,
} from '../models/index';
import {
    AccountVOFromJSON,
    AccountVOToJSON,
    ResponseJsonAccountVOFromJSON,
    ResponseJsonAccountVOToJSON,
} from '../models/index';

export interface SignInRequest {
    accountVO: AccountVO;
}

export interface SignUpRequest {
    accountVO: AccountVO;
}

/**
 * 
 */
export class AuthControllerApi extends runtime.BaseAPI {

    /**
     * 로그인
     */
    async signInRaw(requestParameters: SignInRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseJsonAccountVO>> {
        if (requestParameters['accountVO'] == null) {
            throw new runtime.RequiredError(
                'accountVO',
                'Required parameter "accountVO" was null or undefined when calling signIn().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/auth/signin`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AccountVOToJSON(requestParameters['accountVO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseJsonAccountVOFromJSON(jsonValue));
    }

    /**
     * 로그인
     */
    async signIn(requestParameters: SignInRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseJsonAccountVO> {
        const response = await this.signInRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 회원가입
     */
    async signUpRaw(requestParameters: SignUpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseJsonAccountVO>> {
        if (requestParameters['accountVO'] == null) {
            throw new runtime.RequiredError(
                'accountVO',
                'Required parameter "accountVO" was null or undefined when calling signUp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/auth/signup`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AccountVOToJSON(requestParameters['accountVO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseJsonAccountVOFromJSON(jsonValue));
    }

    /**
     * 회원가입
     */
    async signUp(requestParameters: SignUpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseJsonAccountVO> {
        const response = await this.signUpRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
