/* tslint:disable */
/* eslint-disable */
/**
 * Gym Manager Swagger
 * Gym Manager REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ResponseJsonResponseListVOCalendarVO,
  ResponseJsonResponseListVOMemberVO,
  ResponseJsonResponseListVOPaymentsHistoryVO,
} from '../models/index';
import {
    ResponseJsonResponseListVOCalendarVOFromJSON,
    ResponseJsonResponseListVOCalendarVOToJSON,
    ResponseJsonResponseListVOMemberVOFromJSON,
    ResponseJsonResponseListVOMemberVOToJSON,
    ResponseJsonResponseListVOPaymentsHistoryVOFromJSON,
    ResponseJsonResponseListVOPaymentsHistoryVOToJSON,
} from '../models/index';

/**
 * 
 */
export class DashboardControllerApi extends runtime.BaseAPI {

    /**
     * 이번주 일정 목록 조회
     */
    async selectCalendarVORaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseJsonResponseListVOCalendarVO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/dashboard/calendarWeek`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseJsonResponseListVOCalendarVOFromJSON(jsonValue));
    }

    /**
     * 이번주 일정 목록 조회
     */
    async selectCalendarVO(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseJsonResponseListVOCalendarVO> {
        const response = await this.selectCalendarVORaw(initOverrides);
        return await response.value();
    }

    /**
     * 이번주 새로 등록된 회원 조회
     */
    async selectMemberWeekListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseJsonResponseListVOMemberVO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/dashboard/memberWeek`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseJsonResponseListVOMemberVOFromJSON(jsonValue));
    }

    /**
     * 이번주 새로 등록된 회원 조회
     */
    async selectMemberWeekList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseJsonResponseListVOMemberVO> {
        const response = await this.selectMemberWeekListRaw(initOverrides);
        return await response.value();
    }

    /**
     * 이번주 결제 내역
     */
    async selectWeekListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseJsonResponseListVOPaymentsHistoryVO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/dashboard/payWeek`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseJsonResponseListVOPaymentsHistoryVOFromJSON(jsonValue));
    }

    /**
     * 이번주 결제 내역
     */
    async selectWeekList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseJsonResponseListVOPaymentsHistoryVO> {
        const response = await this.selectWeekListRaw(initOverrides);
        return await response.value();
    }

}
