/* tslint:disable */
/* eslint-disable */
/**
 * Gym Manager Swagger
 * Gym Manager REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ResponseJsonResponseListVOVisitChartVO,
} from '../models/index';
import {
    ResponseJsonResponseListVOVisitChartVOFromJSON,
    ResponseJsonResponseListVOVisitChartVOToJSON,
} from '../models/index';

/**
 * 
 */
export class VisitChartControllerApi extends runtime.BaseAPI {

    /**
     * 요일별 방문 통계
     */
    async selectList3Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseJsonResponseListVOVisitChartVO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/chart/visit/day`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseJsonResponseListVOVisitChartVOFromJSON(jsonValue));
    }

    /**
     * 요일별 방문 통계
     */
    async selectList3(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseJsonResponseListVOVisitChartVO> {
        const response = await this.selectList3Raw(initOverrides);
        return await response.value();
    }

}
