/* tslint:disable */
/* eslint-disable */
/**
 * Gym Manager Swagger
 * Gym Manager REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ResponseJsonResponseListVOMemberVO,
  ResponseJsonResponseListVOVisitHistory,
} from '../models/index';
import {
    ResponseJsonResponseListVOMemberVOFromJSON,
    ResponseJsonResponseListVOMemberVOToJSON,
    ResponseJsonResponseListVOVisitHistoryFromJSON,
    ResponseJsonResponseListVOVisitHistoryToJSON,
} from '../models/index';

export interface SelectMemberRequest {
    lastPhoneNumber: string;
}

export interface SelectMyVisitListRequest {
    memberSeq: number;
}

/**
 * 
 */
export class VisitControllerApi extends runtime.BaseAPI {

    /**
     * 방문 회원 조회
     */
    async selectMemberRaw(requestParameters: SelectMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseJsonResponseListVOMemberVO>> {
        if (requestParameters['lastPhoneNumber'] == null) {
            throw new runtime.RequiredError(
                'lastPhoneNumber',
                'Required parameter "lastPhoneNumber" was null or undefined when calling selectMember().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lastPhoneNumber'] != null) {
            queryParameters['lastPhoneNumber'] = requestParameters['lastPhoneNumber'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/visit`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseJsonResponseListVOMemberVOFromJSON(jsonValue));
    }

    /**
     * 방문 회원 조회
     */
    async selectMember(requestParameters: SelectMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseJsonResponseListVOMemberVO> {
        const response = await this.selectMemberRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 회원별 방문 기록
     */
    async selectMyVisitListRaw(requestParameters: SelectMyVisitListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseJsonResponseListVOVisitHistory>> {
        if (requestParameters['memberSeq'] == null) {
            throw new runtime.RequiredError(
                'memberSeq',
                'Required parameter "memberSeq" was null or undefined when calling selectMyVisitList().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/visit/{memberSeq}`.replace(`{${"memberSeq"}}`, encodeURIComponent(String(requestParameters['memberSeq']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseJsonResponseListVOVisitHistoryFromJSON(jsonValue));
    }

    /**
     * 회원별 방문 기록
     */
    async selectMyVisitList(requestParameters: SelectMyVisitListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseJsonResponseListVOVisitHistory> {
        const response = await this.selectMyVisitListRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
